-- 数据库字段类型更新脚本
-- 将所有varchar类型字段修改为nvarchar类型，确保中文正常显示
-- 执行前请备份数据库

USE hf_metalmarket;
GO

-- 1. 系统字典表 (Sys_Dictionary)
ALTER TABLE Sys_Dictionary ALTER COLUMN DictType NVARCHAR(50) NOT NULL;
ALTER TABLE Sys_Dictionary ALTER COLUMN DictCode NVARCHAR(50) NOT NULL;
ALTER TABLE Sys_Dictionary ALTER COLUMN DictName NVARCHAR(100) NOT NULL;
ALTER TABLE Sys_Dictionary ALTER COLUMN Description NVARCHAR(200) NULL;
GO

-- 2. 角色表 (Role)
ALTER TABLE Role ALTER COLUMN RoleName NVARCHAR(50) NOT NULL;
ALTER TABLE Role ALTER COLUMN RoleCode NVARCHAR(50) NOT NULL;
ALTER TABLE Role ALTER COLUMN Description NVARCHAR(200) NULL;
GO

-- 3. 权限表 (Permission)
ALTER TABLE Permission ALTER COLUMN PermissionName NVARCHAR(100) NOT NULL;
ALTER TABLE Permission ALTER COLUMN PermissionCode NVARCHAR(100) NOT NULL;
ALTER TABLE Permission ALTER COLUMN Description NVARCHAR(200) NULL;
ALTER TABLE Permission ALTER COLUMN ModuleName NVARCHAR(50) NOT NULL;
GO

-- 4. 用户表 (User)
ALTER TABLE [User] ALTER COLUMN Username NVARCHAR(50) NOT NULL;
ALTER TABLE [User] ALTER COLUMN Password NVARCHAR(255) NOT NULL;
ALTER TABLE [User] ALTER COLUMN RealName NVARCHAR(50) NOT NULL;
ALTER TABLE [User] ALTER COLUMN Phone NVARCHAR(20) NULL;
ALTER TABLE [User] ALTER COLUMN Email NVARCHAR(100) NULL;
ALTER TABLE [User] ALTER COLUMN WeChatOpenID NVARCHAR(100) NULL;
GO

-- 5. 商户表 (Merchant)
ALTER TABLE Merchant ALTER COLUMN MerchantName NVARCHAR(100) NOT NULL;
ALTER TABLE Merchant ALTER COLUMN LegalPerson NVARCHAR(50) NOT NULL;
ALTER TABLE Merchant ALTER COLUMN ContactPerson NVARCHAR(50) NOT NULL;
ALTER TABLE Merchant ALTER COLUMN Phone NVARCHAR(20) NOT NULL;
ALTER TABLE Merchant ALTER COLUMN Address NVARCHAR(200) NULL;
ALTER TABLE Merchant ALTER COLUMN MerchantType NVARCHAR(50) NOT NULL;
ALTER TABLE Merchant ALTER COLUMN BusinessLicense NVARCHAR(100) NULL;
ALTER TABLE Merchant ALTER COLUMN TaxRegistration NVARCHAR(100) NULL;
ALTER TABLE Merchant ALTER COLUMN Description NVARCHAR(500) NULL;
ALTER TABLE Merchant ALTER COLUMN Status NVARCHAR(50) NULL;
GO

-- 6. 地块表 (Plot)
ALTER TABLE Plot ALTER COLUMN PlotNumber NVARCHAR(50) NOT NULL;
ALTER TABLE Plot ALTER COLUMN PlotName NVARCHAR(100) NOT NULL;
ALTER TABLE Plot ALTER COLUMN Location NVARCHAR(200) NULL;
ALTER TABLE Plot ALTER COLUMN Description NVARCHAR(500) NULL;
ALTER TABLE Plot ALTER COLUMN ImagePath NVARCHAR(255) NULL;
ALTER TABLE Plot ALTER COLUMN Status NVARCHAR(50) NULL;
GO

-- 7. 合同表 (Contract)
ALTER TABLE Contract ALTER COLUMN ContractNumber NVARCHAR(50) NOT NULL;
ALTER TABLE Contract ALTER COLUMN ContractName NVARCHAR(100) NOT NULL;
ALTER TABLE Contract ALTER COLUMN PaymentMethod NVARCHAR(50) NOT NULL;
ALTER TABLE Contract ALTER COLUMN BusinessType NVARCHAR(50) NOT NULL;
ALTER TABLE Contract ALTER COLUMN Description NVARCHAR(500) NULL;
ALTER TABLE Contract ALTER COLUMN Status NVARCHAR(50) NULL;
GO

-- 8. 电表表 (ElectricityMeter)
ALTER TABLE ElectricityMeter ALTER COLUMN MeterNumber NVARCHAR(50) NOT NULL;
ALTER TABLE ElectricityMeter ALTER COLUMN MeterType NVARCHAR(50) NOT NULL;
ALTER TABLE ElectricityMeter ALTER COLUMN InstallationLocation NVARCHAR(200) NULL;
ALTER TABLE ElectricityMeter ALTER COLUMN Status NVARCHAR(50) NULL;
GO

-- 9. 水表表 (WaterMeter)
ALTER TABLE WaterMeter ALTER COLUMN MeterNumber NVARCHAR(50) NOT NULL;
ALTER TABLE WaterMeter ALTER COLUMN MeterType NVARCHAR(50) NOT NULL;
ALTER TABLE WaterMeter ALTER COLUMN InstallationLocation NVARCHAR(200) NULL;
ALTER TABLE WaterMeter ALTER COLUMN Status NVARCHAR(50) NULL;
GO

-- 10. 换表记录表 (MeterChangeRecord)
ALTER TABLE MeterChangeRecord ALTER COLUMN MeterType NVARCHAR(50) NOT NULL;
ALTER TABLE MeterChangeRecord ALTER COLUMN Reason NVARCHAR(500) NULL;
GO

-- 11. 水电费抄表记录表 (UtilityReading)
ALTER TABLE UtilityReading ALTER COLUMN MeterType NVARCHAR(50) NOT NULL;
ALTER TABLE UtilityReading ALTER COLUMN ReadingMonth NVARCHAR(7) NOT NULL;
GO

-- 12. 费用类型表 (ExpenseType)
ALTER TABLE ExpenseType ALTER COLUMN ExpenseTypeName NVARCHAR(100) NOT NULL;
ALTER TABLE ExpenseType ALTER COLUMN ExpenseTypeCode NVARCHAR(50) NOT NULL;
ALTER TABLE ExpenseType ALTER COLUMN ExpenseDirection NVARCHAR(20) NOT NULL;
ALTER TABLE ExpenseType ALTER COLUMN Description NVARCHAR(200) NULL;
GO

-- 13. 应收账款表 (Receivable)
ALTER TABLE Receivable ALTER COLUMN Description NVARCHAR(500) NULL;
ALTER TABLE Receivable ALTER COLUMN Status NVARCHAR(50) NULL;
ALTER TABLE Receivable ALTER COLUMN ReferenceType NVARCHAR(50) NULL;
GO

-- 14. 应付账款表 (Payable)
ALTER TABLE Payable ALTER COLUMN VendorName NVARCHAR(100) NOT NULL;
ALTER TABLE Payable ALTER COLUMN Description NVARCHAR(500) NULL;
ALTER TABLE Payable ALTER COLUMN Status NVARCHAR(50) NULL;
ALTER TABLE Payable ALTER COLUMN ReferenceType NVARCHAR(50) NULL;
GO

-- 15. 现金流水表 (CashFlow)
ALTER TABLE CashFlow ALTER COLUMN Direction NVARCHAR(20) NOT NULL;
ALTER TABLE CashFlow ALTER COLUMN Description NVARCHAR(500) NULL;
ALTER TABLE CashFlow ALTER COLUMN ReferenceType NVARCHAR(50) NULL;
GO

-- 16. 收款记录表 (CollectionRecord)
ALTER TABLE CollectionRecord ALTER COLUMN PaymentMethod NVARCHAR(50) NOT NULL;
ALTER TABLE CollectionRecord ALTER COLUMN Description NVARCHAR(500) NULL;
GO

-- 17. 付款记录表 (PaymentRecord)
ALTER TABLE PaymentRecord ALTER COLUMN VendorName NVARCHAR(100) NOT NULL;
ALTER TABLE PaymentRecord ALTER COLUMN PaymentMethod NVARCHAR(50) NOT NULL;
ALTER TABLE PaymentRecord ALTER COLUMN Description NVARCHAR(500) NULL;
GO

-- 18. 磅秤表 (Scale)
ALTER TABLE Scale ALTER COLUMN ScaleNumber NVARCHAR(50) NOT NULL;
ALTER TABLE Scale ALTER COLUMN ScaleName NVARCHAR(100) NOT NULL;
ALTER TABLE Scale ALTER COLUMN Location NVARCHAR(200) NOT NULL;
ALTER TABLE Scale ALTER COLUMN Unit NVARCHAR(10) NOT NULL;
ALTER TABLE Scale ALTER COLUMN Status NVARCHAR(50) NULL;
ALTER TABLE Scale ALTER COLUMN Description NVARCHAR(500) NULL;
GO

-- 19. 过磅记录表 (ScaleRecord)
ALTER TABLE ScaleRecord ALTER COLUMN LicensePlate NVARCHAR(50) NULL;
ALTER TABLE ScaleRecord ALTER COLUMN ProductName NVARCHAR(100) NULL;
ALTER TABLE ScaleRecord ALTER COLUMN Operator NVARCHAR(50) NOT NULL;
ALTER TABLE ScaleRecord ALTER COLUMN Description NVARCHAR(500) NULL;
GO

PRINT '所有字段类型修改完成！';
