-- 将所有 VARCHAR 字段修改为 NVARCHAR
-- 执行时间：2026-04-04
-- 总计：18 个字段

USE hf_metalmarket;
GO

ALTER TABLE [Contract] ALTER COLUMN [ContractNumber] NVARCHAR(50);
GO

ALTER TABLE [Contract] ALTER COLUMN [Status] NVARCHAR(50);
GO

ALTER TABLE [ElectricityMeter] ALTER COLUMN [MeterNumber] NVARCHAR(50);
GO

ALTER TABLE [ElectricityMeter] ALTER COLUMN [MeterType] NVARCHAR(50);
GO

ALTER TABLE [ExpenseType] ALTER COLUMN [ExpenseTypeName] NVARCHAR(100);
GO

ALTER TABLE [ExpenseType] ALTER COLUMN [ExpenseTypeCode] NVARCHAR(50);
GO

ALTER TABLE [Merchant] ALTER COLUMN [Status] NVARCHAR(50);
GO

ALTER TABLE [Merchant_Backup_20260331_123354] ALTER COLUMN [Status] NVARCHAR(50);
GO

ALTER TABLE [Payable] ALTER COLUMN [Status] NVARCHAR(50);
GO

ALTER TABLE [Plot] ALTER COLUMN [PlotNumber] NVARCHAR(50);
GO

ALTER TABLE [Plot] ALTER COLUMN [Status] NVARCHAR(50);
GO

ALTER TABLE [Receivable] ALTER COLUMN [Status] NVARCHAR(50);
GO

ALTER TABLE [Scale] ALTER COLUMN [ScaleNumber] NVARCHAR(50);
GO

ALTER TABLE [Scale] ALTER COLUMN [Status] NVARCHAR(50);
GO

ALTER TABLE [User] ALTER COLUMN [Username] NVARCHAR(50);
GO

ALTER TABLE [WaterMeter] ALTER COLUMN [MeterNumber] NVARCHAR(50);
GO

ALTER TABLE [WaterMeter] ALTER COLUMN [MeterType] NVARCHAR(50);
GO

ALTER TABLE [WaterMeter] ALTER COLUMN [Status] NVARCHAR(50);
GO

-- 验证修改结果
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE = 'varchar'
AND TABLE_NAME NOT IN ('sysdiagrams', 'dtproperties');
